/**
 * The seed icon set.
 *
 * Every icon is drawn inside the 9x9 safe area (rows/cols 1–9), leaving the
 * symmetric 1-cell margin. Names, ids, and tags are kebab-case.
 *
 * SINGLE COLOR. The gallery renders every icon in one color, so every seed is
 * authored in one color too — multi-color cell data would be unreachable, and
 * would only surface as a surprise in an exported SVG.
 *
 * DRAWING NOTE: an icon must read as a silhouette. Draw OUTLINES, not filled
 * masses whose meaning depends on internal contrast — a filled envelope with a
 * lighter interior is a plain rectangle in one color; an outlined one survives.
 */

import type { IconDef } from "@/engine/types";
import { defineIcon } from "./authoring";

const SEEDED_AT = "2026-08-17T00:00:00.000Z";

/**
 * THE BASE SET, ADDED 2026-09-15. Everyday interface and system glyphs, chosen
 * from the concept list of Regen Icons (github.com/kazdenc/regen-icons, MIT,
 * Copyright (c) 2026 Regen Icons contributors) and REDRAWN cell by cell on
 * this grid. Nothing was traced or downsampled: Regen draws smooth 2px strokes
 * on 24px, and a shrunk stroke icon is a blur, not a pixel icon.
 *
 * Selective by design. Skipped: anything that duplicates a seed above (their
 * check, x, plus, search, heart and so on); badge variants that differ by a
 * detail too small to survive 11 by 11 (calendar-plus against calendar-x, the
 * file, folder, message, shield, square, sidebar and panel families); and
 * glyphs that did not read at this size after drawing (wrench, paperclip,
 * users, accessibility, command, option).
 */
const REGEN_AT = "2026-09-15T00:00:00.000Z";
const INK = { "#": "#111111" };

export const icons: readonly IconDef[] = [
  /* ---- interface ------------------------------------------------------- */

  defineIcon({
    id: "arrow-right",
    name: "arrow-right",
    category: "interface",
    tags: ["arrow", "right", "next", "forward", "direction"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      ".......#...",
      "........#..",
      ".#########.",
      "........#..",
      ".......#...",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "arrow-left",
    name: "arrow-left",
    category: "interface",
    tags: ["arrow", "left", "back", "previous", "direction"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      "...#.......",
      "..#........",
      ".#########.",
      "..#........",
      "...#.......",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "check",
    name: "check",
    category: "interface",
    tags: ["check", "done", "ok", "tick", "confirm"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".........#.",
      "........##.",
      ".......##..",
      ".#...##....",
      ".##.##.....",
      "..###......",
      "...#.......",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "close",
    name: "close",
    category: "interface",
    tags: ["close", "cancel", "cross", "dismiss", "remove"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".#.......#.",
      ".##.....##.",
      "..##...##..",
      "...##.##...",
      "....###....",
      "...##.##...",
      "..##...##..",
      ".##.....##.",
      ".#.......#.",
      "...........",
    ],
  }),

  defineIcon({
    id: "plus",
    name: "plus",
    category: "interface",
    tags: ["plus", "add", "new", "create", "more"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "....###....",
      "....###....",
      "....###....",
      ".#########.",
      ".#########.",
      ".#########.",
      "....###....",
      "....###....",
      "....###....",
      "...........",
    ],
  }),

  defineIcon({
    id: "menu",
    name: "menu",
    category: "interface",
    tags: ["menu", "list", "hamburger", "nav", "lines"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#########.",
      "...........",
      "...........",
      ".#########.",
      "...........",
      "...........",
      ".#########.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "search",
    name: "search",
    category: "interface",
    tags: ["search", "find", "magnifier", "zoom", "look"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "..####.....",
      ".#....#....",
      ".#....#....",
      ".#....#....",
      "..####.....",
      "....##.....",
      ".....##....",
      "......##...",
      ".......#...",
      "...........",
    ],
  }),

  defineIcon({
    id: "arrow-up",
    name: "arrow-up",
    category: "interface",
    tags: ["arrow", "up", "direction", "top"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "....###....",
      "...#.#.#...",
      ".....#.....",
      ".....#.....",
      ".....#.....",
      ".....#.....",
      ".....#.....",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "arrow-down",
    name: "arrow-down",
    category: "interface",
    tags: ["arrow", "down", "direction", "bottom"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      ".....#.....",
      ".....#.....",
      ".....#.....",
      ".....#.....",
      ".....#.....",
      "...#.#.#...",
      "....###....",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "chevron-right",
    name: "chevron-right",
    category: "interface",
    tags: ["chevron", "right", "next", "caret"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...##......",
      "....##.....",
      ".....##....",
      "......##...",
      ".....##....",
      "....##.....",
      "...##......",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "chevron-left",
    name: "chevron-left",
    category: "interface",
    tags: ["chevron", "left", "back", "caret"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "......##...",
      ".....##....",
      "....##.....",
      "...##......",
      "....##.....",
      ".....##....",
      "......##...",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "chevron-up",
    name: "chevron-up",
    category: "interface",
    tags: ["chevron", "up", "collapse", "caret"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      ".....#.....",
      "....###....",
      "...##.##...",
      "..##...##..",
      "..#.....#..",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "chevron-down",
    name: "chevron-down",
    category: "interface",
    tags: ["chevron", "down", "expand", "caret"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      "..#.....#..",
      "..##...##..",
      "...##.##...",
      "....###....",
      ".....#.....",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "minus",
    name: "minus",
    category: "interface",
    tags: ["minus", "remove", "subtract", "less"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      "...........",
      ".#########.",
      ".#########.",
      ".#########.",
      "...........",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "swap",
    name: "swap",
    category: "interface",
    tags: ["swap", "exchange", "switch", "transfer"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "........#..",
      ".#########.",
      "........#..",
      "...........",
      "..#........",
      ".#########.",
      "..#........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "refresh",
    name: "refresh",
    category: "interface",
    tags: ["refresh", "reload", "sync", "rotate"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "....###.#..",
      "...#...##..",
      "..#...###..",
      "..#........",
      "..#.....#..",
      "..#.....#..",
      "...#...#...",
      "....###....",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "undo",
    name: "undo",
    category: "interface",
    tags: ["undo", "back", "revert", "history"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...#.......",
      "..#######..",
      "...#.....#.",
      ".........#.",
      ".........#.",
      "........#..",
      "...#####...",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "redo",
    name: "redo",
    category: "interface",
    tags: ["redo", "forward", "repeat", "history"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".......#...",
      "..#######..",
      ".#.....#...",
      ".#.........",
      ".#.........",
      "..#........",
      "...#####...",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "enter",
    name: "enter",
    category: "interface",
    tags: ["enter", "return", "corner-down-left", "submit"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".........#.",
      ".........#.",
      ".........#.",
      "...#.....#.",
      "..#......#.",
      ".#########.",
      "..#........",
      "...#.......",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "external-link",
    name: "external-link",
    category: "interface",
    tags: ["external-link", "open", "new-tab", "out"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "......####.",
      ".####...##.",
      ".#.....#.#.",
      ".#....#..#.",
      ".#...#.....",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "filter",
    name: "filter",
    category: "interface",
    tags: ["filter", "funnel", "sort", "narrow"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".#########.",
      "..#.....#..",
      "...#...#...",
      "....#.#....",
      "....#.#....",
      "....#.#....",
      "....#.#....",
      "....###....",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "list",
    name: "list",
    category: "interface",
    tags: ["list", "items", "bullets", "rows"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#.#######.",
      "...........",
      "...........",
      ".#.#######.",
      "...........",
      "...........",
      ".#.#######.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "layout-grid",
    name: "layout-grid",
    category: "interface",
    tags: ["layout-grid", "grid", "apps", "tiles", "dashboard"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".####.####.",
      ".#..#.#..#.",
      ".#..#.#..#.",
      ".####.####.",
      "...........",
      ".####.####.",
      ".#..#.#..#.",
      ".#..#.#..#.",
      ".####.####.",
      "...........",
    ],
  }),

  defineIcon({
    id: "dots",
    name: "dots",
    category: "interface",
    tags: ["dots", "more", "ellipsis", "options"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      "...........",
      "...........",
      "..#..#..#..",
      "...........",
      "...........",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "eye",
    name: "eye",
    category: "interface",
    tags: ["eye", "view", "show", "visible", "watch"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      "...#####...",
      "..#..#..#..",
      ".#..###..#.",
      "..#..#..#..",
      "...#####...",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "eye-off",
    name: "eye-off",
    category: "interface",
    tags: ["eye-off", "hide", "hidden", "invisible"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      "...........",
      ".#.......#.",
      "..##...##..",
      "..#.###.#..",
      ".....#.....",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "lock",
    name: "lock",
    category: "interface",
    tags: ["lock", "secure", "private", "closed", "password"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "....###....",
      "...#...#...",
      "...#...#...",
      ".#########.",
      ".#.......#.",
      ".#...#...#.",
      ".#...#...#.",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "unlock",
    name: "unlock",
    category: "interface",
    tags: ["unlock", "open", "public", "unsecure"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "....###....",
      "...#...#...",
      "...#.......",
      ".#########.",
      ".#.......#.",
      ".#...#...#.",
      ".#...#...#.",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "settings",
    name: "settings",
    category: "interface",
    tags: ["settings", "gear", "preferences", "cog", "options"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "..#.###.#..",
      "...#####...",
      "..##...##..",
      ".###...###.",
      "..##...##..",
      "...#####...",
      "..#.###.#..",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "home",
    name: "home",
    category: "interface",
    tags: ["home", "house", "start", "main"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "....#.#....",
      "...#...#...",
      "..#.....#..",
      ".#.......#.",
      "..#.....#..",
      "..#.###.#..",
      "..#.#.#.#..",
      "..###.###..",
      "...........",
    ],
  }),

  defineIcon({
    id: "trash",
    name: "trash",
    category: "interface",
    tags: ["trash", "delete", "bin", "remove", "discard"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "....###....",
      ".#########.",
      "..#.....#..",
      "..#.#.#.#..",
      "..#.#.#.#..",
      "..#.#.#.#..",
      "..#.#.#.#..",
      "..#.....#..",
      "...#####...",
      "...........",
    ],
  }),

  defineIcon({
    id: "pencil",
    name: "pencil",
    category: "interface",
    tags: ["pencil", "edit", "write", "draw"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".......##..",
      "......#..#.",
      ".....#..#..",
      "....#..#...",
      "...#..#....",
      "..#..#.....",
      ".#..#......",
      ".#.#.......",
      ".##........",
      "...........",
    ],
  }),

  defineIcon({
    id: "copy",
    name: "copy",
    category: "interface",
    tags: ["copy", "duplicate", "clone", "paste"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "....######.",
      "....#....#.",
      "....#....#.",
      ".######..#.",
      ".#....#..#.",
      ".#....####.",
      ".#....#....",
      ".#....#....",
      ".######....",
      "...........",
    ],
  }),

  defineIcon({
    id: "download",
    name: "download",
    category: "interface",
    tags: ["download", "save", "get", "arrow-down"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      ".....#.....",
      ".....#.....",
      "...#.#.#...",
      "....###....",
      ".....#.....",
      "...........",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "upload",
    name: "upload",
    category: "interface",
    tags: ["upload", "send", "put", "arrow-up"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "....###....",
      "...#.#.#...",
      ".....#.....",
      ".....#.....",
      ".....#.....",
      "...........",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "link",
    name: "link",
    category: "interface",
    tags: ["link", "chain", "url", "attach"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      "..##...##..",
      ".#..#.#..#.",
      ".#.#####.#.",
      ".#..#.#..#.",
      "..##...##..",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "bookmark",
    name: "bookmark",
    category: "interface",
    tags: ["bookmark", "save", "saved", "ribbon"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "..#######..",
      "..#.....#..",
      "..#.....#..",
      "..#.....#..",
      "..#.....#..",
      "..#.....#..",
      "..#..#..#..",
      "..#.#.#.#..",
      "..##...##..",
      "...........",
    ],
  }),

  defineIcon({
    id: "flag",
    name: "flag",
    category: "interface",
    tags: ["flag", "report", "mark", "milestone"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".########..",
      ".#......#..",
      ".#.....#...",
      ".#......#..",
      ".########..",
      ".#.........",
      ".#.........",
      ".#.........",
      ".#.........",
      "...........",
    ],
  }),

  defineIcon({
    id: "tag",
    name: "tag",
    category: "interface",
    tags: ["tag", "label", "price", "category"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".######....",
      ".#.....#...",
      ".#......#..",
      ".#.#.....#.",
      ".#......#..",
      ".#.....#...",
      ".######....",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "pin",
    name: "pin",
    category: "interface",
    tags: ["pin", "location", "map-pin", "place", "marker"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      "..#.....#..",
      ".#..###..#.",
      ".#..#.#..#.",
      ".#..###..#.",
      "..#.....#..",
      "...#...#...",
      "....#.#....",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "info",
    name: "info",
    category: "interface",
    tags: ["info", "information", "about", "help"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      ".##.....##.",
      ".#...#...#.",
      ".#.......#.",
      ".#...#...#.",
      ".#...#...#.",
      ".#...#...#.",
      ".##.....##.",
      "...#####...",
      "...........",
    ],
  }),

  defineIcon({
    id: "help",
    name: "help",
    category: "interface",
    tags: ["help", "question", "support", "faq"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      ".##.....##.",
      ".#..###..#.",
      ".#.....#.#.",
      ".#....#..#.",
      ".#...#...#.",
      ".#.......#.",
      ".##..#..##.",
      "...#####...",
      "...........",
    ],
  }),

  defineIcon({
    id: "alert",
    name: "alert",
    category: "interface",
    tags: ["alert", "warning", "caution", "danger", "triangle"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "....#.#....",
      "....#.#....",
      "...#.#.#...",
      "...#.#.#...",
      "..#..#..#..",
      "..#.....#..",
      ".#...#...#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "checkbox",
    name: "checkbox",
    category: "interface",
    tags: ["checkbox", "square-check", "done", "task", "selected"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".#########.",
      ".#.......#.",
      ".#.......#.",
      ".#.....#.#.",
      ".#....#..#.",
      ".#.#.#...#.",
      ".#..#....#.",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "cursor",
    name: "cursor",
    category: "interface",
    tags: ["cursor", "pointer", "mouse", "click", "select"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".#.........",
      ".##........",
      ".#.#.......",
      ".#..#......",
      ".#...#.....",
      ".#.###.....",
      ".##.#......",
      ".#...#.....",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "bulb",
    name: "bulb",
    category: "interface",
    tags: ["bulb", "idea", "light", "tip", "hint"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      "..#.....#..",
      ".#.......#.",
      ".#..#.#..#.",
      ".#...#...#.",
      "..#..#..#..",
      "...#####...",
      "...#...#...",
      "....###....",
      "...........",
    ],
  }),

  defineIcon({
    id: "credit-card",
    name: "credit-card",
    category: "interface",
    tags: ["credit-card", "card", "payment", "billing"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#########.",
      ".#.......#.",
      ".#########.",
      ".#.......#.",
      ".#.###...#.",
      ".#.......#.",
      ".#########.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "wallet",
    name: "wallet",
    category: "interface",
    tags: ["wallet", "money", "payment", "balance"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".######....",
      ".#.....#...",
      ".#########.",
      ".#....####.",
      ".#....#.##.",
      ".#....####.",
      ".#.......#.",
      ".#########.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "shopping-bag",
    name: "shopping-bag",
    category: "interface",
    tags: ["shopping-bag", "bag", "shop", "cart", "store"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "....###....",
      "...#...#...",
      ".#########.",
      ".#.#...#.#.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  /* ---- media ----------------------------------------------------------- */

  defineIcon({
    id: "play",
    name: "play",
    category: "media",
    tags: ["play", "start", "media", "video", "triangle"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...#.......",
      "...##......",
      "...###.....",
      "...####....",
      "...#####...",
      "...####....",
      "...###.....",
      "...##......",
      "...#.......",
      "...........",
    ],
  }),

  defineIcon({
    id: "pause",
    name: "pause",
    category: "media",
    tags: ["pause", "stop", "media", "halt", "break"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...##.##...",
      "...##.##...",
      "...##.##...",
      "...##.##...",
      "...##.##...",
      "...##.##...",
      "...##.##...",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "volume",
    name: "volume",
    category: "media",
    tags: ["volume", "sound", "audio", "speaker", "loud"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "......#....",
      ".....##.#..",
      "..######.#.",
      "..######.#.",
      "..######.#.",
      ".....##.#..",
      "......#....",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "camera",
    name: "camera",
    category: "media",
    tags: ["camera", "photo", "picture", "snapshot"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...###.....",
      ".#########.",
      ".#.......#.",
      ".#..###..#.",
      ".#..#.#..#.",
      ".#..###..#.",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "image",
    name: "image",
    category: "media",
    tags: ["image", "photo", "picture", "gallery"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#########.",
      ".#.......#.",
      ".#.##....#.",
      ".#.##..#.#.",
      ".#....####.",
      ".#..#.####.",
      ".#.#######.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "video",
    name: "video",
    category: "media",
    tags: ["video", "film", "record", "movie"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      ".######....",
      ".#....#..#.",
      ".#....#.##.",
      ".#....#.##.",
      ".#....#..#.",
      ".######....",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "music",
    name: "music",
    category: "media",
    tags: ["music", "note", "song", "audio"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "....######.",
      "....######.",
      "....#....#.",
      "....#....#.",
      "....#....#.",
      "....#....#.",
      "..###..###.",
      ".####.####.",
      "..##...##..",
      "...........",
    ],
  }),

  defineIcon({
    id: "mic",
    name: "mic",
    category: "media",
    tags: ["mic", "microphone", "record", "voice"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "....###....",
      "...#...#...",
      "...#...#...",
      "...#...#...",
      ".#..###..#.",
      "..#.....#..",
      "...#####...",
      ".....#.....",
      "...#####...",
      "...........",
    ],
  }),

  defineIcon({
    id: "headphones",
    name: "headphones",
    category: "media",
    tags: ["headphones", "audio", "listen", "music"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      "..#.....#..",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".###...###.",
      ".###...###.",
      ".###...###.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "skip-back",
    name: "skip-back",
    category: "media",
    tags: ["skip-back", "previous", "rewind", "media"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "..#.....#..",
      "..#....##..",
      "..#...###..",
      "..#..####..",
      "..#...###..",
      "..#....##..",
      "..#.....#..",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "skip-forward",
    name: "skip-forward",
    category: "media",
    tags: ["skip-forward", "next", "media", "track"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "..#.....#..",
      "..##....#..",
      "..###...#..",
      "..####..#..",
      "..###...#..",
      "..##....#..",
      "..#.....#..",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "volume-off",
    name: "volume-off",
    category: "media",
    tags: ["volume-off", "mute", "silent", "sound-off"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".....#.....",
      "....##.....",
      ".#####.#.#.",
      ".#####..#..",
      ".#####.#.#.",
      "....##.....",
      ".....#.....",
      "...........",
      "...........",
    ],
  }),

  /* ---- arcade ---------------------------------------------------------- */

  defineIcon({
    id: "heart",
    name: "heart",
    category: "arcade",
    tags: ["heart", "life", "health", "love", "favorite"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "..##...##..",
      ".#########.",
      ".#########.",
      ".#########.",
      ".#########.",
      "..#######..",
      "...#####...",
      "....###....",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "coin",
    name: "coin",
    category: "arcade",
    tags: ["coin", "credit", "token", "money", "score"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      ".##.....##.",
      ".#.......#.",
      ".#..###..#.",
      ".#..#.#..#.",
      ".#..###..#.",
      ".#.......#.",
      ".##.....##.",
      "...#####...",
      "...........",
    ],
  }),

  defineIcon({
    id: "ghost",
    name: "ghost",
    category: "arcade",
    tags: ["ghost", "enemy", "spooky", "arcade", "maze"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      "..#.....#..",
      ".#..#.#..#.",
      ".#..#.#..#.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#.#.#.#.#.",
      "...........",
    ],
  }),

  defineIcon({
    id: "trophy",
    name: "trophy",
    category: "arcade",
    tags: ["trophy", "win", "award", "prize", "high-score"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".#########.",
      ".#.......#.",
      ".#.......#.",
      "..#######..",
      "....###....",
      ".....#.....",
      ".....#.....",
      "...#####...",
      "..#######..",
      "...........",
    ],
  }),

  defineIcon({
    id: "robot",
    name: "robot",
    category: "arcade",
    tags: ["robot", "agent", "bot", "android", "ai"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "...#####...",
      "..#.....#..",
      "..#.#.#.#..",
      ".##.....##.",
      "..#.###.#..",
      "..#.....#..",
      "...#####...",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "target",
    name: "target",
    category: "arcade",
    tags: ["target", "aim", "goal", "bullseye"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      ".##.....##.",
      ".#..###..#.",
      ".#.#...#.#.",
      ".#.#.#.#.#.",
      ".#.#...#.#.",
      ".#..###..#.",
      ".##.....##.",
      "...#####...",
      "...........",
    ],
  }),

  defineIcon({
    id: "diamond",
    name: "diamond",
    category: "arcade",
    tags: ["diamond", "gem", "jewel", "treasure", "loot"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...#####...",
      "..#.#.#.#..",
      ".#########.",
      "..#.....#..",
      "...#...#...",
      "....#.#....",
      ".....#.....",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "cube",
    name: "cube",
    category: "arcade",
    tags: ["cube", "box", "block", "3d", "package"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "...##.##...",
      ".##.....##.",
      ".#.##.##.#.",
      ".#...#...#.",
      ".#...#...#.",
      ".##..#..##.",
      "...##.##...",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "sparkle",
    name: "sparkle",
    category: "arcade",
    tags: ["sparkle", "power-up", "magic", "shine", "new"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      ".....#.....",
      "....#.#....",
      "...#...#...",
      ".##.....##.",
      "...#...#...",
      "....#.#....",
      ".....#.....",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "key",
    name: "key",
    category: "arcade",
    tags: ["key", "unlock", "password", "access", "item"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      "..###......",
      ".#...#.....",
      ".#...#####.",
      ".#...#.#.#.",
      "..###......",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "shield",
    name: "shield",
    category: "arcade",
    tags: ["shield", "armor", "protect", "security", "defense"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".#########.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      "..#.....#..",
      "...#...#...",
      "....#.#....",
      ".....#.....",
      "...........",
    ],
  }),

  /* ---- system ---------------------------------------------------------- */

  defineIcon({
    id: "floppy-disk",
    name: "floppy-disk",
    category: "system",
    tags: ["floppy", "disk", "save", "storage", "file"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".#########.",
      ".#..###..#.",
      ".#..#.#..#.",
      ".#..###..#.",
      ".#.......#.",
      ".#.#####.#.",
      ".#.#...#.#.",
      ".#.#####.#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "folder",
    name: "folder",
    category: "system",
    tags: ["folder", "directory", "files", "storage", "open"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "..####.....",
      ".#########.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#########.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "battery",
    name: "battery",
    category: "system",
    tags: ["battery", "power", "charge", "energy", "level"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#######...",
      ".#.....#...",
      ".#.###.#...",
      ".#.###.###.",
      ".#.###.#...",
      ".#.....#...",
      ".#######...",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "archive",
    name: "archive",
    category: "system",
    tags: ["archive", "box", "storage", "store"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".#########.",
      ".#.......#.",
      ".#########.",
      "..#.....#..",
      "..#.###.#..",
      "..#.....#..",
      "..#.....#..",
      "..#.....#..",
      "..#######..",
      "...........",
    ],
  }),

  defineIcon({
    id: "calendar",
    name: "calendar",
    category: "system",
    tags: ["calendar", "date", "schedule", "event"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#...#...",
      ".#########.",
      ".#########.",
      ".#.......#.",
      ".#.#.#.#.#.",
      ".#.......#.",
      ".#.#.#.#.#.",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "clock",
    name: "clock",
    category: "system",
    tags: ["clock", "time", "hour", "schedule"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      ".##.....##.",
      ".#...#...#.",
      ".#...#...#.",
      ".#...###.#.",
      ".#.......#.",
      ".#.......#.",
      ".##.....##.",
      "...#####...",
      "...........",
    ],
  }),

  defineIcon({
    id: "clipboard",
    name: "clipboard",
    category: "system",
    tags: ["clipboard", "paste", "notes", "list"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "....###....",
      ".##.#.#.##.",
      ".#..###..#.",
      ".#.......#.",
      ".#.#####.#.",
      ".#.......#.",
      ".#.###...#.",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "code",
    name: "code",
    category: "system",
    tags: ["code", "developer", "brackets", "html"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "......#....",
      "...#..##...",
      "..#..#..#..",
      ".#...#...#.",
      "..#..#..#..",
      "...##..#...",
      "....#......",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "terminal",
    name: "terminal",
    category: "system",
    tags: ["terminal", "console", "command", "shell", "prompt"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".#########.",
      ".#.......#.",
      ".#.#.....#.",
      ".#..#....#.",
      ".#.#.....#.",
      ".#...###.#.",
      ".#.......#.",
      ".#########.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "database",
    name: "database",
    category: "system",
    tags: ["database", "storage", "data", "sql"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      ".##.....##.",
      ".#.#####.#.",
      ".#.......#.",
      ".##.....##.",
      ".#.#####.#.",
      ".#.......#.",
      ".##.....##.",
      "...#####...",
      "...........",
    ],
  }),

  defineIcon({
    id: "server",
    name: "server",
    category: "system",
    tags: ["server", "host", "rack", "hardware"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#########.",
      ".#.#.....#.",
      ".#########.",
      "...........",
      ".#########.",
      ".#.#.....#.",
      ".#########.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "git-branch",
    name: "git-branch",
    category: "system",
    tags: ["git-branch", "branch", "version", "fork"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".###...###.",
      ".#.#...#.#.",
      ".###...###.",
      "..#.....#..",
      "..#....#...",
      "..#..##....",
      ".####......",
      ".#.#.......",
      ".###.......",
      "...........",
    ],
  }),

  defineIcon({
    id: "bug",
    name: "bug",
    category: "system",
    tags: ["bug", "issue", "error", "debug", "insect"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#...#...",
      "....###....",
      ".#.#...#.#.",
      "..#.....#..",
      ".##.....##.",
      "..#.....#..",
      ".##.....##.",
      "..#.....#..",
      "...#####...",
      "...........",
    ],
  }),

  defineIcon({
    id: "file",
    name: "file",
    category: "system",
    tags: ["file", "document", "page", "text"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "..####.....",
      "..#..##....",
      "..#..#.#...",
      "..#..####..",
      "..#.....#..",
      "..#.###.#..",
      "..#.....#..",
      "..#.###.#..",
      "..#######..",
      "...........",
    ],
  }),

  defineIcon({
    id: "keyboard",
    name: "keyboard",
    category: "system",
    tags: ["keyboard", "type", "input", "keys"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#########.",
      ".#.......#.",
      ".#.#.#.#.#.",
      ".#.......#.",
      ".#.#####.#.",
      ".#.......#.",
      ".#########.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "monitor",
    name: "monitor",
    category: "system",
    tags: ["monitor", "screen", "display", "desktop"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".#########.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#########.",
      ".....#.....",
      "...#####...",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "smartphone",
    name: "smartphone",
    category: "system",
    tags: ["smartphone", "phone", "mobile", "device"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      "...#...#...",
      "...#...#...",
      "...#...#...",
      "...#...#...",
      "...#...#...",
      "...#####...",
      "...#.#.#...",
      "...#####...",
      "...........",
    ],
  }),

  defineIcon({
    id: "power",
    name: "power",
    category: "system",
    tags: ["power", "on", "off", "shutdown", "start"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "..#..#..#..",
      ".#...#...#.",
      ".#...#...#.",
      ".#.......#.",
      ".#.......#.",
      "..#.....#..",
      "...#####...",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "wifi",
    name: "wifi",
    category: "system",
    tags: ["wifi", "wireless", "signal", "network", "internet"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "..#######..",
      ".#.......#.",
      "...#####...",
      "..#.....#..",
      "....###....",
      "...#...#...",
      "...........",
      ".....#.....",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "adjustments",
    name: "adjustments",
    category: "system",
    tags: ["adjustments", "sliders", "controls", "tune", "mixer"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "..#..#..#..",
      "..#..#..#..",
      ".###.#..#..",
      "..#..#..#..",
      "..#.###.#..",
      "..#..#..#..",
      "..#..#.###.",
      "..#..#..#..",
      "..#..#..#..",
      "...........",
    ],
  }),

  defineIcon({
    id: "chart-bar",
    name: "chart-bar",
    category: "system",
    tags: ["chart-bar", "chart", "stats", "analytics", "graph"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".......##..",
      ".......##..",
      "....##.##..",
      "....##.##..",
      ".##.##.##..",
      ".##.##.##..",
      ".##.##.##..",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "chart-pie",
    name: "chart-pie",
    category: "system",
    tags: ["chart-pie", "pie", "stats", "share", "graph"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      ".##..#####.",
      ".#...#####.",
      ".#...#####.",
      ".#...#####.",
      ".#.......#.",
      ".#.......#.",
      ".##.....##.",
      "...#####...",
      "...........",
    ],
  }),

  /* ---- communication --------------------------------------------------- */

  defineIcon({
    id: "mail",
    name: "mail",
    category: "communication",
    tags: ["mail", "email", "envelope", "message", "inbox"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#########.",
      ".##.....##.",
      ".#.##.##.#.",
      ".#..###..#.",
      ".#.......#.",
      ".#.......#.",
      ".#########.",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "chat",
    name: "chat",
    category: "communication",
    tags: ["chat", "message", "bubble", "talk", "comment"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      ".#########.",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".#########.",
      "...##......",
      "..##.......",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "bell",
    name: "bell",
    category: "communication",
    tags: ["bell", "notification", "alert", "ring", "reminder"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "....#.#....",
      "...#...#...",
      "...#...#...",
      "..#.....#..",
      "..#.....#..",
      ".#########.",
      "....###....",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "at-sign",
    name: "at-sign",
    category: "communication",
    tags: ["at-sign", "at", "email", "mention", "handle"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      "..#.....#..",
      ".#..###..#.",
      ".#.#..#..#.",
      ".#.#..#..#.",
      ".#..#####..",
      ".#.........",
      "..#........",
      "...######..",
      "...........",
    ],
  }),

  defineIcon({
    id: "phone",
    name: "phone",
    category: "communication",
    tags: ["phone", "call", "handset", "contact"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".###.......",
      ".###.......",
      ".##........",
      ".##........",
      "..##.......",
      "...##......",
      "....###.##.",
      ".....#####.",
      ".......###.",
      "...........",
    ],
  }),

  defineIcon({
    id: "send",
    name: "send",
    category: "communication",
    tags: ["send", "paper-plane", "message", "submit"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      ".##........",
      ".#.##......",
      ".#...##....",
      ".#.....##..",
      ".#.####..#.",
      ".#.....##..",
      ".#...##....",
      ".#.##......",
      ".##........",
      "...........",
    ],
  }),

  defineIcon({
    id: "inbox",
    name: "inbox",
    category: "communication",
    tags: ["inbox", "tray", "received", "messages"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "..#######..",
      ".#.......#.",
      ".#.......#.",
      ".#.......#.",
      ".###...###.",
      ".#..###..#.",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  defineIcon({
    id: "user",
    name: "user",
    category: "communication",
    tags: ["user", "person", "profile", "account"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "....###....",
      "...#...#...",
      "...#...#...",
      "....###....",
      "...........",
      "...#####...",
      "..#.....#..",
      ".#.......#.",
      ".#########.",
      "...........",
    ],
  }),

  /* ---- nature ---------------------------------------------------------- */

  defineIcon({
    id: "sun",
    name: "sun",
    category: "nature",
    tags: ["sun", "weather", "light", "day", "bright"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "..#.....#..",
      "....###....",
      "...#####...",
      ".#.#####.#.",
      "...#####...",
      "....###....",
      "..#.....#..",
      ".....#.....",
      "...........",
    ],
  }),

  defineIcon({
    id: "moon",
    name: "moon",
    category: "nature",
    tags: ["moon", "night", "crescent", "dark", "sleep"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "....###....",
      "...#...#...",
      "..#...##...",
      "..#..##....",
      "..#..#.....",
      "..#..##....",
      "..#...##...",
      "...#...#...",
      "....###....",
      "...........",
    ],
  }),

  defineIcon({
    id: "star",
    name: "star",
    category: "nature",
    tags: ["star", "favorite", "rating", "night", "sparkle"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      ".....#.....",
      "....###....",
      "....###....",
      ".#########.",
      ".#########.",
      "..#######..",
      "...#####...",
      "..##.#.##..",
      ".##.....##.",
      "...........",
    ],
  }),

  defineIcon({
    id: "cloud",
    name: "cloud",
    category: "nature",
    tags: ["cloud", "weather", "sky", "overcast", "storage"],
    createdAt: SEEDED_AT,
    palette: INK,
    art: [
      "...........",
      "...........",
      "...........",
      "....###....",
      "...######..",
      ".#########.",
      ".#########.",
      "..#######..",
      "...........",
      "...........",
      "...........",
    ],
  }),

  defineIcon({
    id: "zap",
    name: "zap",
    category: "nature",
    tags: ["zap", "lightning", "bolt", "power", "energy"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "......#....",
      ".....##....",
      "....##.....",
      "...##......",
      "..#######..",
      "......##...",
      ".....##....",
      "....##.....",
      "....#......",
      "...........",
    ],
  }),

  defineIcon({
    id: "globe",
    name: "globe",
    category: "nature",
    tags: ["globe", "world", "earth", "web", "internet"],
    createdAt: REGEN_AT,
    palette: INK,
    art: [
      "...........",
      "...#####...",
      ".##.#.#.##.",
      ".#..#.#..#.",
      ".#..#.#..#.",
      ".#########.",
      ".#..#.#..#.",
      ".#..#.#..#.",
      ".##.#.#.##.",
      "...#####...",
      "...........",
    ],
  }),
];

/** Look up one icon by its stable id. */
export function getIcon(id: string): IconDef | undefined {
  return icons.find((icon) => icon.id === id);
}
